name: download-and-convert

on:
  issues:
    types:
      - labeled

jobs:
  youtube-dl:
    if: github.event.label.name == 'youtube'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Install ffmpeg
        run: sudo apt install ffmpeg -y

      - name: Create output directory
        run: mkdir -p files/musics

      - name: Download audio from YouTube
        run: yt-dlp --extract-audio -P files/musics "${{ github.event.issue.body }}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated update from GitHub Actions: Downloaded audio from YouTube"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed'
            });         branch: master
