name: Download Telegram Music

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  download-music:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install telebot

      - name: Set environment variable
        run: echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run music downloader
        run: |
          source venv/bin/activate
          python3.12 ./files/scripts/tel-music.py
    
      - name: install convertor
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: audio convertor
        run: ./files/scripts/convertor.sh

      - name: Make changes (example)
        run: |
          git config user.name "shabane"
          git config user.email "m.mohamadshabane@gmail.com"
          git add files/musics
          git commit -m "[music] added ${{ github.event.issue.number }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
